[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)][string]$OvmsExe,
    [Parameter(Mandatory = $true)][string]$ModelPath,
    [string]$ModelName = 'gemma4-26-heretic',
    [string]$RepoRoot = (Join-Path $PSScriptRoot '..\..'),
    [string]$ShortRoot = 'g5',
    [string]$Label = '2026.5-candidate',
    [ValidateSet('E', 'Stable', 'PrefixCache')][string]$Profile = 'E',
    [ValidateSet('JINJA', 'MINJA')][string]$ChatTemplateMode = 'JINJA',
    [int]$RestPort = 8000,
    [int]$GrpcPort = 9000,
    [int]$ReadinessTimeoutSeconds = 180,
    [switch]$Wait
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

$root = (Resolve-Path -LiteralPath $RepoRoot).Path
$ovms = (Resolve-Path -LiteralPath $OvmsExe).Path
$model = (Resolve-Path -LiteralPath $ModelPath).Path
if (-not (Test-Path -LiteralPath $ovms -PathType Leaf)) { throw "ovms.exe not found: $ovms" }
if (-not (Test-Path -LiteralPath $model -PathType Container)) { throw "model directory not found: $model" }

function Test-PortOpen([int]$Port) {
    $client = New-Object System.Net.Sockets.TcpClient
    try {
        $async = $client.BeginConnect('127.0.0.1', $Port, $null, $null)
        if (-not $async.AsyncWaitHandle.WaitOne(300)) { return $false }
        $client.EndConnect($async)
        return $true
    } catch { return $false } finally { $client.Close() }
}

if (Test-PortOpen $RestPort) { throw "REST port $RestPort is already in use; refusing to kill an existing process." }
if (Test-PortOpen $GrpcPort) { throw "gRPC port $GrpcPort is already in use; refusing to kill an existing process." }

$runtimeDir = Join-Path $root ("tmp\gemmamonster-ovms\" + $Label + '-' + $Profile.ToLowerInvariant())
New-Item -ItemType Directory -Path $runtimeDir -Force | Out-Null
$modelProto = $model.Replace('\', '/')
$runtimeProto = ([System.IO.Path]::GetFullPath($runtimeDir)).Replace('\', '/')

$pluginConfig = [ordered]@{ DYNAMIC_QUANTIZATION_GROUP_SIZE = '0' }
$enablePrefixCaching = $false
$cacheSizeLine = '      cache_size: 0'
$profileNote = 'B2-style correctness isolation'

switch ($Profile) {
    'E' {
        # Current target-machine working profile. Do not silently inherit cache_size
        # from B2/C because the exact E cache_size was never committed in the freeze.
        $pluginConfig.KV_CACHE_PRECISION = 'u8'
        $enablePrefixCaching = $true
        $cacheSizeLine = ''
        $profileNote = 'current working E: u8 KV cache + prefix caching; cache_size intentionally unpinned'
    }
    'Stable' {
        $enablePrefixCaching = $false
        $cacheSizeLine = '      cache_size: 0'
        $profileNote = 'B2-style correctness isolation'
    }
    'PrefixCache' {
        $enablePrefixCaching = $true
        $cacheSizeLine = '      cache_size: 8'
        $profileNote = 'C-style prefix-cache comparison'
    }
}
$pluginJson = ($pluginConfig | ConvertTo-Json -Compress)
$prefixLiteral = if ($enablePrefixCaching) { 'true' } else { 'false' }
$cacheBlock = if ([string]::IsNullOrWhiteSpace($cacheSizeLine)) { '' } else { $cacheSizeLine + "`n" }

$graph = @"
# Generated by scripts/gemma4/launch-gemma4-candidate.ps1
# Profile: $Profile; $profileNote; candidate: $Label
input_stream: "HTTP_REQUEST_PAYLOAD:input"
output_stream: "HTTP_RESPONSE_PAYLOAD:output"

node: {
  name: "LLMExecutor"
  calculator: "HttpLLMCalculator"
  input_stream: "LOOPBACK:loopback"
  input_stream: "HTTP_REQUEST_PAYLOAD:input"
  input_side_packet: "LLM_NODE_RESOURCES:llm"
  input_side_packet: "LLM_NODE_EXECUTION_CONTEXTS:llm_ctx"
  output_stream: "LOOPBACK:loopback"
  output_stream: "HTTP_RESPONSE_PAYLOAD:output"
  input_stream_info: {
    tag_index: "LOOPBACK:0"
    back_edge: true
  }
  node_options: {
    [type.googleapis.com / mediapipe.LLMCalculatorOptions]: {
      models_path: "$modelProto"
      device: "GPU"
      plugin_config: '$pluginJson'
      max_num_seqs: 1
      enable_prefix_caching: $prefixLiteral
$cacheBlock      pipeline_type: VLM_CB
      chat_template_mode: $ChatTemplateMode
      max_tokens_limit: 65536
    }
  }
  input_stream_handler {
    input_stream_handler: "SyncSetInputStreamHandler"
    options {
      [mediapipe.SyncSetInputStreamHandlerOptions.ext] {
        sync_set { tag_index: "LOOPBACK:0" }
      }
    }
  }
}
"@
$graphPath = Join-Path $runtimeDir 'graph.pbtxt'
$graph | Set-Content -LiteralPath $graphPath -Encoding UTF8

$config = [ordered]@{
    model_config_list = @()
    mediapipe_config_list = @(
        [ordered]@{ name = $ModelName; base_path = $runtimeProto }
    )
}
$configPath = Join-Path $runtimeDir 'config.json'
$config | ConvertTo-Json -Depth 6 | Set-Content -LiteralPath $configPath -Encoding UTF8

$env:OVMS_GRAPH_QUEUE_MAX_SIZE = '0'
$pathPrepend = New-Object System.Collections.Generic.List[string]
$openVinoRoot = "C:\$ShortRoot\openvino"
foreach ($p in @(
    (Join-Path $openVinoRoot 'runtime\bin'),
    (Join-Path $openVinoRoot 'runtime\3rdparty\tbb\bin'),
    'C:\opt\Python312',
    'C:\opt\Python312\Scripts'
)) {
    if (Test-Path -LiteralPath $p) { $pathPrepend.Add($p) }
}
$versionsPath = Join-Path $root 'versions.mk'
if (Test-Path -LiteralPath $versionsPath) {
    $versionsText = Get-Content -LiteralPath $versionsPath -Raw -Encoding UTF8
    if ($versionsText -match '(?m)^OPENCV_VERSION\s+\?=\s+([^\s]+)') {
        $opencv = "C:\opt\opencv_$($Matches[1])\x64\vc17\bin"
        if (Test-Path -LiteralPath $opencv) { $pathPrepend.Add($opencv) }
    }
}
if ($pathPrepend.Count -gt 0) { $env:PATH = (@($pathPrepend) -join ';') + ';' + $env:PATH }

if ($ChatTemplateMode -eq 'JINJA') {
    $pythonHome = 'C:\opt\Python312'
    if (Test-Path -LiteralPath $pythonHome) { $env:PYTHONHOME = $pythonHome }
    $pythonPaths = New-Object System.Collections.Generic.List[string]
    foreach ($p in @(
        (Join-Path $root 'bazel-out\x64_windows-opt\bin\src\python\binding'),
        'C:\opt\Python312\Lib\site-packages'
    )) {
        if (Test-Path -LiteralPath $p) { $pythonPaths.Add($p) }
    }
    if ($pythonPaths.Count -gt 0) { $env:PYTHONPATH = @($pythonPaths) -join ';' }
}

$logPath = Join-Path $runtimeDir 'ovms.log'
$args = @(
    '--config_path', $configPath,
    '--rest_port', [string]$RestPort,
    '--port', [string]$GrpcPort,
    '--log_level', 'DEBUG',
    '--log_path', $logPath
)
$launchRecord = [ordered]@{
    schema_version = 2
    launched_at_utc = [DateTime]::UtcNow.ToString('o')
    label = $Label
    profile = $Profile
    profile_note = $profileNote
    chat_template_mode = $ChatTemplateMode
    ovms_exe = $ovms
    ovms_sha256 = (Get-FileHash -LiteralPath $ovms -Algorithm SHA256).Hash.ToLowerInvariant()
    model_path = $model
    model_name = $ModelName
    rest_port = $RestPort
    grpc_port = $GrpcPort
    graph_path = $graphPath
    config_path = $configPath
    device = 'GPU'
    pipeline_type = 'VLM_CB'
    max_num_seqs = 1
    plugin_config = $pluginConfig
    enable_prefix_caching = $enablePrefixCaching
    cache_size = if ($Profile -eq 'E') { $null } elseif ($Profile -eq 'Stable') { 0 } else { 8 }
    max_tokens_limit = 65536
    command = @($ovms) + $args
}
$launchRecord | ConvertTo-Json -Depth 8 | Set-Content -LiteralPath (Join-Path $runtimeDir 'launch.json') -Encoding UTF8

Write-Host "Launching $Label / Profile $Profile"
Write-Host "  profile: $profileNote"
Write-Host "  binary:  $ovms"
Write-Host "  model:   $model"
Write-Host "  config:  $configPath"
Write-Host "  REST:    http://127.0.0.1:$RestPort"
$process = Start-Process -FilePath $ovms -ArgumentList $args -PassThru -NoNewWindow
$launchRecord.pid = $process.Id
$launchRecord | ConvertTo-Json -Depth 8 | Set-Content -LiteralPath (Join-Path $runtimeDir 'launch.json') -Encoding UTF8

$deadline = [DateTime]::UtcNow.AddSeconds($ReadinessTimeoutSeconds)
$ready = $false
while ([DateTime]::UtcNow -lt $deadline) {
    if ($process.HasExited) { throw "OVMS exited before readiness with code $($process.ExitCode). See $logPath" }
    try {
        $response = Invoke-WebRequest -Uri "http://127.0.0.1:$RestPort/v2/health/ready" -TimeoutSec 5 -UseBasicParsing
        if ($response.StatusCode -eq 200) { $ready = $true; break }
    } catch { }
    Start-Sleep -Seconds 2
}
if (-not $ready) { throw "OVMS did not become ready within $ReadinessTimeoutSeconds seconds. PID=$($process.Id), log=$logPath" }

Write-Host "OVMS READY pid=$($process.Id)"
Write-Host "Generated runtime directory: $runtimeDir"
if ($Wait) {
    Wait-Process -Id $process.Id
    exit $process.ExitCode
}
$process
