[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)][string]$CandidateRoot,
    [Parameter(Mandatory = $true)][string]$ModelPath,
    [string]$ModelName = 'gemma4-26-heretic',
    [string]$RepoRoot = (Join-Path $PSScriptRoot '..\..'),
    [string]$Label = '2026.5-candidate',
    [ValidateSet('E', 'Stable', 'PrefixCache')][string]$Profile = 'E',
    [ValidateSet('JINJA', 'MINJA')][string]$ChatTemplateMode = 'JINJA',
    [int]$RestPort = 8000,
    [int]$GrpcPort = 9000,
    [int]$ReadinessTimeoutSeconds = 180,
    [switch]$Wait
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

$root = (Resolve-Path -LiteralPath $RepoRoot).Path
$verifyScript = Join-Path $root 'scripts\gemma4\Test-CandidateArtifact.ps1'
$artifact = & $verifyScript -CandidateRoot $CandidateRoot
$candidate = $artifact.CandidateRoot
$packageRoot = $artifact.PackageRoot
$ovms = $artifact.OvmsExe
$model = (Resolve-Path -LiteralPath $ModelPath).Path
if (-not (Test-Path -LiteralPath $model -PathType Container)) { throw "model directory not found: $model" }

function Test-PortOpen([int]$Port) {
    $client = New-Object System.Net.Sockets.TcpClient
    try {
        $async = $client.BeginConnect('127.0.0.1', $Port, $null, $null)
        if (-not $async.AsyncWaitHandle.WaitOne(300)) { return $false }
        $client.EndConnect($async)
        return $true
    } catch { return $false } finally { $client.Close() }
}

if (Test-PortOpen $RestPort) { throw "REST port $RestPort is already in use; refusing to kill an existing process." }
if (Test-PortOpen $GrpcPort) { throw "gRPC port $GrpcPort is already in use; refusing to kill an existing process." }

$runtimeDir = Join-Path $root ("tmp\gemmamonster-ovms\" + $Label + '-' + $Profile.ToLowerInvariant())
New-Item -ItemType Directory -Path $runtimeDir -Force | Out-Null
$modelProto = $model.Replace('\', '/')
$runtimeProto = ([System.IO.Path]::GetFullPath($runtimeDir)).Replace('\', '/')

$pluginConfig = [ordered]@{ DYNAMIC_QUANTIZATION_GROUP_SIZE = '0' }
$enablePrefixCaching = $false
$cacheSizeLine = '      cache_size: 0'
$profileNote = 'B2-style correctness isolation'

switch ($Profile) {
    'E' {
        $pluginConfig.KV_CACHE_PRECISION = 'u8'
        $enablePrefixCaching = $true
        $cacheSizeLine = ''
        $profileNote = 'current working E: u8 KV cache + prefix caching; cache_size intentionally unpinned'
    }
    'Stable' {
        $enablePrefixCaching = $false
        $cacheSizeLine = '      cache_size: 0'
        $profileNote = 'B2-style correctness isolation'
    }
    'PrefixCache' {
        $enablePrefixCaching = $true
        $cacheSizeLine = '      cache_size: 8'
        $profileNote = 'C-style prefix-cache comparison'
    }
}
$pluginJson = ($pluginConfig | ConvertTo-Json -Compress)
$prefixLiteral = if ($enablePrefixCaching) { 'true' } else { 'false' }
$cacheBlock = if ([string]::IsNullOrWhiteSpace($cacheSizeLine)) { '' } else { $cacheSizeLine + "`n" }

$graph = @"
# Generated by scripts/gemma4/launch-gemma4-candidate.ps1
# Profile: $Profile; $profileNote; candidate: $Label
input_stream: "HTTP_REQUEST_PAYLOAD:input"
output_stream: "HTTP_RESPONSE_PAYLOAD:output"

node: {
  name: "LLMExecutor"
  calculator: "HttpLLMCalculator"
  input_stream: "LOOPBACK:loopback"
  input_stream: "HTTP_REQUEST_PAYLOAD:input"
  input_side_packet: "LLM_NODE_RESOURCES:llm"
  input_side_packet: "LLM_NODE_EXECUTION_CONTEXTS:llm_ctx"
  output_stream: "LOOPBACK:loopback"
  output_stream: "HTTP_RESPONSE_PAYLOAD:output"
  input_stream_info: {
    tag_index: "LOOPBACK:0"
    back_edge: true
  }
  node_options: {
    [type.googleapis.com / mediapipe.LLMCalculatorOptions]: {
      models_path: "$modelProto"
      device: "GPU"
      plugin_config: '$pluginJson'
      max_num_seqs: 1
      enable_prefix_caching: $prefixLiteral
$cacheBlock      pipeline_type: VLM_CB
      chat_template_mode: $ChatTemplateMode
      max_tokens_limit: 65536
    }
  }
  input_stream_handler {
    input_stream_handler: "SyncSetInputStreamHandler"
    options {
      [mediapipe.SyncSetInputStreamHandlerOptions.ext] {
        sync_set { tag_index: "LOOPBACK:0" }
      }
    }
  }
}
"@
$graphPath = Join-Path $runtimeDir 'graph.pbtxt'
$graph | Set-Content -LiteralPath $graphPath -Encoding UTF8

$config = [ordered]@{
    model_config_list = @()
    mediapipe_config_list = @(
        [ordered]@{ name = $ModelName; base_path = $runtimeProto }
    )
}
$configPath = Join-Path $runtimeDir 'config.json'
$config | ConvertTo-Json -Depth 6 | Set-Content -LiteralPath $configPath -Encoding UTF8

$env:OVMS_GRAPH_QUEUE_MAX_SIZE = '0'

# Candidate v1 is a self-contained Windows runtime. Put only package-local runtime
# directories ahead of the inherited PATH; do not inject C:\g5, C:\opt OpenVINO,
# or another machine-level dependency root.
$pathPrepend = New-Object System.Collections.Generic.List[string]
foreach ($p in @(
    $packageRoot,
    (Join-Path $packageRoot 'python'),
    (Join-Path $packageRoot 'python\Scripts')
)) {
    if (Test-Path -LiteralPath $p) { $pathPrepend.Add($p) }
}
if ($pathPrepend.Count -gt 0) { $env:PATH = (@($pathPrepend) -join ';') + ';' + $env:PATH }

if ($ChatTemplateMode -eq 'JINJA') {
    $pythonHome = Join-Path $packageRoot 'python'
    if (Test-Path -LiteralPath (Join-Path $pythonHome 'Lib\encodings') -PathType Container) {
        $env:PYTHONHOME = $pythonHome
    } else {
        Remove-Item Env:PYTHONHOME -ErrorAction SilentlyContinue
    }
    $sitePackages = Join-Path $pythonHome 'Lib\site-packages'
    if (Test-Path -LiteralPath $sitePackages -PathType Container) {
        $env:PYTHONPATH = $sitePackages
    } else {
        Remove-Item Env:PYTHONPATH -ErrorAction SilentlyContinue
    }
}

$logPath = Join-Path $runtimeDir 'ovms.log'
$args = @(
    '--config_path', $configPath,
    '--rest_port', [string]$RestPort,
    '--port', [string]$GrpcPort,
    '--log_level', 'DEBUG',
    '--log_path', $logPath
)
$launchRecord = [ordered]@{
    schema_version = 3
    launched_at_utc = [DateTime]::UtcNow.ToString('o')
    label = $Label
    profile = $Profile
    profile_note = $profileNote
    chat_template_mode = $ChatTemplateMode
    candidate_contract = $artifact.Contract
    candidate_root = $candidate
    candidate_git_sha = $artifact.GitSha
    candidate_manifest = $artifact.ManifestPath
    package_root = $packageRoot
    ovms_exe = $ovms
    ovms_sha256 = $artifact.OvmsSha256
    runtime_policy = 'SELF_CONTAINED_PACKAGE_ONLY'
    model_path = $model
    model_name = $ModelName
    rest_port = $RestPort
    grpc_port = $GrpcPort
    graph_path = $graphPath
    config_path = $configPath
    device = 'GPU'
    pipeline_type = 'VLM_CB'
    max_num_seqs = 1
    plugin_config = $pluginConfig
    enable_prefix_caching = $enablePrefixCaching
    cache_size = if ($Profile -eq 'E') { $null } elseif ($Profile -eq 'Stable') { 0 } else { 8 }
    max_tokens_limit = 65536
    command = @($ovms) + $args
}
$launchRecord | ConvertTo-Json -Depth 8 | Set-Content -LiteralPath (Join-Path $runtimeDir 'launch.json') -Encoding UTF8

Write-Host "Launching $Label / Profile $Profile"
Write-Host "  profile:   $profileNote"
Write-Host "  candidate: $candidate"
Write-Host "  binary:    $ovms"
Write-Host "  SHA256:    $($artifact.OvmsSha256)"
Write-Host "  model:     $model"
Write-Host "  config:    $configPath"
Write-Host "  REST:      http://127.0.0.1:$RestPort"
$process = Start-Process -FilePath $ovms -ArgumentList $args -WorkingDirectory $packageRoot -PassThru -NoNewWindow
$launchRecord.pid = $process.Id
$launchRecord | ConvertTo-Json -Depth 8 | Set-Content -LiteralPath (Join-Path $runtimeDir 'launch.json') -Encoding UTF8

$deadline = [DateTime]::UtcNow.AddSeconds($ReadinessTimeoutSeconds)
$ready = $false
while ([DateTime]::UtcNow -lt $deadline) {
    if ($process.HasExited) { throw "OVMS exited before readiness with code $($process.ExitCode). See $logPath" }
    try {
        $response = Invoke-WebRequest -Uri "http://127.0.0.1:$RestPort/v2/health/ready" -TimeoutSec 5 -UseBasicParsing
        if ($response.StatusCode -eq 200) { $ready = $true; break }
    } catch { }
    Start-Sleep -Seconds 2
}
if (-not $ready) { throw "OVMS did not become ready within $ReadinessTimeoutSeconds seconds. PID=$($process.Id), log=$logPath" }

# Prove that the running candidate resolved its core runtime from the immutable
# package rather than from C:\g5, C:\opt, or any other ambient PATH entry.
$runtimeVerification = & $verifyScript -CandidateRoot $candidate -ExpectedGitSha $artifact.GitSha -VerifyLoadedRuntime
$launchRecord.loaded_runtime_verified = $true
$launchRecord.loaded_runtime_verified_pid = $runtimeVerification.ProcessId
$launchRecord | ConvertTo-Json -Depth 8 | Set-Content -LiteralPath (Join-Path $runtimeDir 'launch.json') -Encoding UTF8

Write-Host "OVMS READY pid=$($process.Id)"
Write-Host "Candidate runtime verified self-contained: $packageRoot"
Write-Host "Generated runtime directory: $runtimeDir"
if ($Wait) {
    Wait-Process -Id $process.Id
    exit $process.ExitCode
}
$process
